"""empty message

Revision ID: befc6e4f49bf
Revises: fd76a4d245c6
Create Date: 2022-09-29 13:47:02.027067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'befc6e4f49bf'
down_revision = 'fd76a4d245c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    op.drop_column('user', 'is_author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_author', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
