"""empty message

Revision ID: dae5a1f49930
Revises: befc6e4f49bf
Create Date: 2022-10-02 22:45:59.163938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae5a1f49930'
down_revision = 'befc6e4f49bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
